Feature Selection

In [12]:
from sklearn.feature_selection import f_regression

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [14]:
data = pd.read_csv("C:\\Users\\yume\\Desktop\\LinearRegression_Jupyter\\salary_data.csv")

In [15]:
x = data["YearsExperience"].values.reshape(-1,1)
y = data['Salary'].values.reshape(-1,1)
f_regression(x,y)

C:\Users\yume\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(array([622.50720263]), array([1.14306811e-20]))

In [16]:
p_values = f_regression(x,y)[1]
p_values

C:\Users\yume\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1.14306811e-20])

In [17]:
p_values.round(3)

array([0.])

summary table

In [28]:
reg_summary = pd.DataFrame(data = ['YearsExperience'], columns = ['Features'])
reg_summary
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
reg_summary['Coeficients'] = reg.coef_
reg_summary['p_values'] = p_values
reg_summary

Features  Coeficients      p_values
0  YearsExperience  9449.962321  1.143068e-20

In [31]:
new_data = pd.DataFrame(data = [['6'],['7']], columns = ['YearsExperience'])
new_data

YearsExperience
0               6
1               7

In [32]:
reg.predict(new_data)

array([[82491.9741274 ],
       [91941.93644885]])